version: '3.8'

services:
  backend:
    image: quanganhngo2107/agent_project-backend:latest 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agent_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    env_file:
      - .env  # Dòng này giúp truyền file .env vào trong Docker
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload